### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by monkeyscript** [monkeyscript/ngx-morse#7]
Unit tests with maximum code coverage are to be added.

Prefer people with experience in Angular unit tests and npm package dev.

**Comment by hemangsk** [comment]
Hey @monkeyscript , I'd like to work on this. I've some experience with Angular unit testing and would like to dive deeper.
There are two methods in ngxMorseService which are to be covered with tests, if I understand correctly.

**Comment by monkeyscript** [comment]
@hemangsk Yeah. The service file contains all the important functions.

**Comment by monkeyscript** [comment]
#9
